dist: trusty
sudo: true
language: c++
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0
    packages:
    - cmake
    - cmake-data
    - gcc-5
    - g++-5
    - llvm-5.0
    - llvm-5.0-dev

script:
    - rm -rf build
    - mkdir build
    - pushd build
    - export CC=gcc-5
    - export CXX=g++-5
    - cmake -DCMAKE_BUILD_TYPE=Debug -DLLVM_DIR="/usr/lib/llvm-5.0/lib/cmake/llvm/" ..
    - cmake --build .
    - popd

